[package]
name = "anchor-collector"
version = "0.0.2"
edition = "2021"
authors = ["Oto Brglez <otobrglez@gmail.com>"]

[dependencies]
rand = "0.8.5"
ureq = { version = "2.5.0", features = ["json", "cookies"] }
serde = { version = "1", features = ["derive"] }
