[package]
name = "anchor-collector"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
ureq = { version = "2.5.0", features = ["json", "cookies"] }
serde = { version = "1", features = ["derive"] }
