name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: name/app
      
      -
        name: Login to DockerHub
        # if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      #- name: Build
      #  run: cargo build --verbose
      #- name: Run tests
      #  run: cargo test --verbose
